In [3]:
import numpy as np
x=[80,83,100]
y=[70,20,50]
correlation=np.correlate(x,y)


In [5]:
correlation

array([11860])

In [11]:
X=np.asarray(x)
Y=np.asarray(y)
covariance=np.cov(X,Y)

In [13]:
covariance

array([[343.        , 260.        ],
       [260.        , 633.33333333]])

In [15]:
print(X)

[ 80  63 100]


In [17]:
print(Y)

[70 20 50]


In [19]:
print(X,Y)

[ 80  63 100] [70 20 50]
