In [5]:
import numpy as np
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2
print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:",division)
array3 = np.array([[1,2,3], [4,5,6]])
print("Array 3:")
print(array3)
mean = np.mean(array3)
print("Mean:", mean)
median = np.median(array3)
print("Median:",median)
std_dev = np.std(array3)
print("Standard deviation:",std_dev)
reshaped_array = array3.reshape(3,2)
print("Reshaped_array:")
print(reshaped_array)
transpose_array = np.transpose(array3)
print("Transpose_array:")
print(transpose_array)


Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Array 3:
[[1 2 3]
 [4 5 6]]
Mean: 3.5
Median: 3.5
Standard deviation: 1.707825127659933
Reshaped_array:
[[1 2]
 [3 4]
 [5 6]]
Transpose_array:
[[1 4]
 [2 5]
 [3 6]]
